### ISSUE TITLE
Build wheel

### ISSUE THREAD

**Issue by PythonCoderAS** [bwhmather/ssort#107]
ssort has no wheel, so pip will always build a wheel from scratch. This is fine normally but not if using QEmu to build for another architecture, such as in CI. Since the package is written in pure Python, only a single wheel should need to be built. 

If possible, could a wheel please be built?

**Comment by bwhmather** [comment]
I was pretty sure I had fixed this, but apparently PR was never merged.  Fixed in version 0.12.1, which I have just pushed.  Thank you for bringing this to my attention.
