### ISSUE TITLE
Request: flag(s) to take input from stdin and send output to stdout, rather than in-place editing

### ISSUE THREAD

**Issue by AndydeCleyre** [bwhmather/ssort#118]
This came up for me specifically trying to integrate `ssort` into the Zed editor, which expects any provided external formatter to output the new content to stdout, and take input from stdin.

**Comment by bwhmather** [comment]
That sounds very reasonable.  If you're up for writing a PR then I would be enthusiastic to help get it merged and released.  I think it should just be a matter of a few small tweaks to `_main.py`.

**Comment by AndydeCleyre** [comment]
Thanks, I'll submit something!

I think it'll be sufficient to have a mode that reads stdin, and in that case writes stdout (no need for a separate stdout option).

Which would you prefer of

1. `--stdin`
2. A single dash `-` where the file args usually go
3. Detect when content is being piped
4. Something else

?

**Comment by bwhmather** [comment]
I had assumed `--stdout` but I think you are right that there's no need.  Looks like `isort` and `black` both go with option 2 so might as well be consistent with that.

**Comment by AndydeCleyre** [comment]
Completed in 0.14.0 with #119 !

For anyone finding this, passing `-` as a file arg now means read stdin and send formatted result to stdout.
