### ISSUE TITLE
Example in the documentation

### ISSUE THREAD

**Issue by Honeypot95** [bwhmather/ssort#17]
I came here after reading about ssort on hackernews. Is there anyway to can put an example of some sort in the documentation? I did not comprehend exactly what this linter does after reading the description, and it dawned on me that even though I may be able to comprehend after I play around with it a bit, the documentation can be improved.

**Comment by bwhmather** [comment]
Have added a short example, but not completely happy with it yet.  Will leave this ticket open.  Thank you for reporting, I agree completely.

**Comment by bwhmather** [comment]
Still no better examples yet, but have renamed the examples folder to indicate that it's really only interesting for testing.
