### ISSUE TITLE
Skip files listed in .gitignore

### ISSUE THREAD

**Issue by kevlened** [bwhmather/ssort#23]
I ran `ssort` at the root of my project and it started sorting the files in my `venv` directory. (incidentally, this threw on `venv/lib/python3.10/site-packages/blib2to3/pgen2/parse.py`)

**Comment by bwhmather** [comment]
I think this is a good idea.  It also matches what black and isort do, which is important.

Relevant bits of code from black:
  - https://github.com/psf/black/blob/b4a6bb08fa704facbf3397f95b3216e13c3c964a/src/black/files.py
  
Relevant bits of code from isort:
  - https://github.com/PyCQA/isort/blob/c6a41965247a858a0afd848fbebfca18b8983917/isort/files.py
  - https://github.com/PyCQA/isort/blob/c6a41965247a858a0afd848fbebfca18b8983917/isort/settings.py#L588-L637
  
The black module looks particularly straightforward and the project is license compatible, so it might make sense to just copy the whole lot in.

**Comment by bwhmather** [comment]
I found a version of `blib2to3` in the black project, but it doesn't trigger any errors for me.  Would you be able to upload your copy?  It sounds like a good candidate for the examples directory.

**Comment by jgberry** [comment]
@bwhmather I'm taking a crack at this based on the work done in the `exclude` branch. It seems that, at a bare minimum, we'll need to add a dependency on `pathspec` to handle `.gitignore` parsing. What are your thoughts on 3rd party dependencies?

**Comment by bwhmather** [comment]
Let's not go full npm, but I have no problem with pulling in pathspec.  I would expect that 100% of people who install ssort will also install black, which means that if pathspec's developer decides to start using it to mine bitcoin then the battle is already lost.

**Comment by bwhmather** [comment]
Released as part of 0.11.3.  Thank you @jgberry
