### ISSUE TITLE
missing .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by yunkaili** [bwhmather/ssort#24]
try to add ssort in pre-commit config, but a InvalidManifestError is reported
find out the project is missing .pre-commit-hooks.yaml
hope to add a .pre-commit-hooks.yaml in the next released version

**Comment by bwhmather** [comment]
I presume you are referring to this: https://pre-commit.com/.  I must confess that this isn't something that I have used before, and it doesn't fit into my own workflow.  It appears to be widely supported though, and I don't see any obvious downsides to including it.  I would be happy to take a PR on condition that someone else answers bug reports on it.  Would you be interested?

**Comment by yunkaili** [comment]
> 

thats it, it shold be a easy one. 
i see a PR has been reported, good job guys
