### ISSUE TITLE
Coverage tests for singledispatch visitors

### ISSUE THREAD

**Issue by bwhmather** [bwhmather/ssort#34]
It would be helpful to have tests that check that every type of ast node is covered by every type of visitor.  This would help when adding support for new python versions, and may uncover some existing bugs.

**Comment by bwhmather** [comment]
This may be obviated by #36 and equivalent from @jgberry.

**Comment by jgberry** [comment]
Yes, I believe this has been mostly addressed as visitors no longer need to support every AST node type, only the node types which are relevant to their behavior.

There is perhaps room to improve coverage testing for `_ast.iter_child_nodes` as it still needs to handle every AST node type.
