### ISSUE TITLE
Error when sorting overloaded functions that are being used 

### ISSUE THREAD

**Issue by yasserfarouk** [bwhmather/ssort#37]
## The problem
If I have a function that is overloaded using the standard `typing.overload` operator that also happens to be called earlier in the file, ssort will move the implementation up but not the overload decleration which will lead to errors.

## example:
Here is a minimum example (let's call this example.py)

```python
from typing import overload

def g():
    f(1)

@overload
def f(x: int) -> int:
    ...


@overload
def f(x: str) -> str:
    ...


def f(x: int | str) -> int | str:
    print(x)
    return x


if __name__ == "__main__":
    f(5)
```

It is important that the method `f` is being used by `g` which is defined before it. If that was not the case, no error will happen.

Running `ssort --check --diff example.py` on this file gives:

```python
ERROR: 'etc/overload.py' is incorrectly sorted
--- etc/overload.py:before
+++ etc/overload.py:after
@@ -1,4 +1,9 @@
 from typing import overload
+
+
+def f(x: int | str) -> int | str:
+    print(x)
+    return x

 def g():
     f(1)
@@ -11,8 +16,3 @@
 @overload
 def f(x: str) -> str:
     ...
-
-
-def f(x: int | str) -> int | str:
-    print(x)
-    return x
1 file would be resorted
``` 

Now running 
```bash
ssort test.py
python test.py
```

will give:
```python
Traceback (most recent call last):
  File "/Users/yasser/code/projects/negmas/etc/overload.py", line 23, in <module>
    f(5)
  File "/Users/yasser/.pyenv/versions/3.9.2/lib/python3.9/typing.py", line 1562, in _overload_dummy
    raise NotImplementedError(
NotImplementedError: You should not call an overloaded function. A series of @overload-decorated functions outside a stub module should always be followed by an implementation that is not @overload-ed.
```

##  Possible solution
One possible solution is to move all overload declaration with the actual implementation:

```python
from __future__ import annotations
from typing import overload

@overload
def f(x: int) -> int:
    ...


@overload
def f(x: str) -> str:
    ...

def f(x: int | str) -> int | str:
    print(x)
    return x

def g():
    f(1)


if __name__ == "__main__":
    f(5)
```

### Alternative solution
If an overloaded method is being called within the file, ignore this method when sorting.

**Comment by bwhmather** [comment]
Definitely a bug.  I think the reason for it is that we only create a dependency link between a "deferred" requirement (in this case the call to `f` in `g`) and the _last_ binding in the file.  Previous bindings are ignored.

I've been able to come up with other examples that trigger the same bad behaviour.

Running `ssort` on the following code:
```python
def f():
    return l
l = []
l += 1
```
will give:
```python
l += 1
def f():
    return l
l = []
```

I think the solution is to create dependency links between bindings.  Hopefully it will be straightforward.
