### ISSUE TITLE
Line ending problem

### ISSUE THREAD

**Issue by EricE** [bwhmather/ssort#61]
Just tried ssort on a Windows 10 machine.  I copied your example and saved it with CRLF line endings then ran ssort.  It rewrote the line endings without removing the old ones (added a CR for each CRLF), here are some screenshots from Notepad++:

Initial file:
![image](https://user-images.githubusercontent.com/126238/160184608-502dc33d-6e53-4ca9-b83b-f35394464694.png)

After:
![image](https://user-images.githubusercontent.com/126238/160184686-7174bee4-f2a8-474e-b348-01f4d61c07cb.png)

**Comment by bwhmather** [comment]
Ouch.  That's an interesting one.  Suspect the bug was introduced when we fixed support for different encodings.  Hopefully the same path can be used to fix it.  Will have an experiment, but may need to ask for your help to test on windows.

**Comment by bwhmather** [comment]
Have the start of an approach in #63.  Will pick it up again at some point tomorrow and try to get a release out over the weekend.

**Comment by bwhmather** [comment]
Fix released as part of 0.11.5.  @EricE - Please let me know if you still have issues.
