### ISSUE TITLE
__init__ method order

### ISSUE THREAD

**Issue by Niccolum** [bwhmather/ssort#68]
I'm used to writing __init__ always first inside a class.  Is it possible to make this setting configurable?
For example, like isort works with import order - FUTURE,STDLIB,THIRDPARTY,AIRFLOW,FIRSTPARTY,LOCALFOLDER. You can make something like INIT, PUBLIC, PRIVATE, PROTECTED, MAGIC

**Comment by bwhmather** [comment]
Hi @Niccolum - I'm afraid that I think the answer to this one is no.  I can't say that the current order is objectively better, but part of the goal of this project is to improve consistency across the entire ecosystem.  I would prefer not to add any configuration at all without a compelling reason.  With that said, I think you'll find that the ssort order isn't too far off what you are used to.  We have the same split between INIT and MAGIC, and most classes don't have that many properties.  I know it's a terrible answer but hopefully, if this approach is successful, you will never need to get used to a third sort order.

**Comment by Niccolum** [comment]
Thanks for answer. It's your lib, and our opinions can be different and this is OK :) Thanks for the answer
