### ISSUE TITLE
Error when walrus operator variables referenced in lambda functions

### ISSUE THREAD

**Issue by joouha** [bwhmather/ssort#73]
Hi Ben,

When running `ssort` on the following:

```python
f = lambda: (a := 1) + a
```

I get the following error:

```
ERROR: unresolved dependency 'a' in /home/josiah/test.py: line 1, column 23
1 file was not sortable
```

Thanks

**Comment by bwhmather** [comment]
Have pushed a new patch release, 0.11.6, with @jgberry's fix.  Thank you both.

**Comment by bwhmather** [comment]
Also, I've just realised it's you @joouha.  Thank you for sticking with ssort after the shenanigans with deleting comments from empty files.  We're getting there.
