### ISSUE TITLE
Bug: unresolved dependency '__path__' in __init__.py

### ISSUE THREAD

**Issue by cgahr** [bwhmather/ssort#78]
Consider the following package
```bash
> tree pkg
pkg
└── __init__.py

0 directories, 1 file
```
where `__init__.py` contains the following code:
```bash
print(__path__)
```

This package is a valid python package and the following code runs:
```python
> python -c "import pkg"
['/home/<user>/ssort/pkg']
```

However, if I run `ssort` in the `pkg` folder, I get the following error:
```bash
> ssort
ERROR: unresolved dependency '__path__' in __init__.py: line 1, column 6
1 file was not sortable
```

This should not happen since `__path__` is defined in the `__init__.py` file of a package.

Instead, consider the package
```bash
pkg
├── file.py
└── __init__.py

0 directories, 2 files
```
with
```python
# __init__.py
from . import file

# file.py
print(__path__)
```
Then the following code fails
```bash
> python -c "import pkg"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/<user>/ssort/pkg/__init__.py", line 2, in <module>
    from . import file
  File "/home/<user>/ssort/pkg/file.py", line 2, in <module>
    print(__path__)
          ^^^^^^^^
NameError: name '__path__' is not defined. Did you mean: '__name__'?
```
and `ssort` rightfully complains
```bash
> ssort
ERROR: unresolved dependency '__path__' in pkg/file.py: line 2, column 6
1 file was left unchanged, 1 file was not sortable
```

Altogether, the first case is a bug.

TL, DR: in the `__init__.py` file of a package the variable `__path__` is defined.

**Comment by bwhmather** [comment]
Yup.  This is definitely a bug.  If you don't mind, I'll leave this one open so that you have something to do once we've figure out your test issue in the other PR.

**Comment by jgberry** [comment]
As mentioned in #85, I think option 1 is actually perfectly acceptable, if not preferable.
