### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by cgahr** [bwhmather/ssort#83]
If I add py311 to `tox.ini`, i.e.
```ini
[tox]
envlist = py38,py39,py310,py311,black,isort,ssort,pyflakes,pylint,mypy
```
the tox suite fails.

The error boils down to
```
E       NotImplementedError: AST traversal for 'TryStar' is not implemented
```
which is new syntax in python 3.11 and to
```
{'BaseExceptionGroup', 'ExceptionGroup'}
```
not being in `MODULE_BUILTINS`.

**Comment by bwhmather** [comment]
Changed title as tests are working as hoped.  Unless we can come up with a way to automatically support arbitrary future syntax changes, support will need to be added manually.
