### ISSUE TITLE
Bug: positional-only argument in method of class

### ISSUE THREAD

**Issue by cgahr** [bwhmather/ssort#90]
In `_method_requirements.py` the function `def _get_method_requirements_for_function_def(...): ...` contains a bug.

The following class using positional-only arguments is not parsed correctly:
```python
class C:
    def fun(self, arg0, /, arg1):
        ...
```
If I understand the code correctly, in this case the name of the `self` argument is not parsed correctly.

**Comment by bwhmather** [comment]
Does that mean the result of `def _get_method_requirements_for_function_def(...):` currently includes `self`?  If so, I think that your assessment is correct.
