### ISSUE TITLE
Bug: test_function_def_requirements_shadowed_after is wrong

### ISSUE THREAD

**Issue by cgahr** [bwhmather/ssort#94]
In `test_requirements.py` the following test is wrong:
```python
def test_function_def_requirements_shadowed_after():
    node = _parse(
        """
        def function():
            a
            a = b
        """
    )
    assert _dep_names(node) == ["b"]
```
The requirements of `function` are `["a", "b"]`.

This code 
```python
b = 1

def fun():
    a
    a = b

fun()
```
shows that both `a` and `b` are indeed a requirement since it raises an `UnboundLocalError` and thus is not valid.

**Comment by jgberry** [comment]
I don't think this is correct. Let's consider what "requirements" are. Within ssort we use the term "requirements" to refer to all variables of a statement that are NOT bound by the statement itself. That is, any variable whose definition is outside the scope of a statement is a "requirement" of that statement. So, within the context of a function definition, the requirements of that function definition are all non local variables used in that function. I think the error you get when executing the function in question is very telling here. It's an `UnboundLocalError`, meaning `a` is indeed a local variable and therefore not a requirement of the function. This specific case is pretty tricky though and requires you to know that global and local variables of the same name cannot both be used with a functions body.

**Comment by cgahr** [comment]
Interesting. 
So basically the difference between a "runtime" requirement (i.e. when we execute the function) and a "parse-time" requirement (i.e. when the function definition is executed).

Does the current implementation differ between those two types of requirements?

**Comment by bwhmather** [comment]
> So basically the difference between a "runtime" requirement (i.e. when we execute the function) and a "parse-time" requirement (i.e. when the function definition is executed).

Not quite, although that is also a thing and very closely related.  This test is about scope (i.e. _where_ a variable is loaded from) and both python and ssort determine this statically.

We do distinguish between "runtime" and "parse-time" requirements as you describe them (i.e. _when_ a variable is loaded) when sorting methods:
  - https://github.com/bwhmather/ssort/blob/f9869861343c0f120e15502b2b01b4c6c158e20c/src/ssort/_ssort.py#L234-L236
  - https://github.com/bwhmather/ssort/blob/f9869861343c0f120e15502b2b01b4c6c158e20c/src/ssort/_ssort.py#L307-L312
  
When sorting everything else, we assume that the only place where a distinction between "runtime" and "parse-time" requirements is interesting is when there is a cycle.  In this case we leave it to the programmer to figure out a working order.
